WheelsMarket/WheelsMarket/Controllers/BrandController.cs
using Microsoft.AspNetCore.Mvc;
using WheelsMarket.Services.VehicleTypeSections.ViewModel;
using WheelsMarket.Services.VehicleTypeSections;
using WheelsMarket.Services.Brands;
using WheelsMarket.Services.Brands.ViewModel;
using WheelsMarket.Data.Models;
using WheelsMarket.Services.VehicleTypeTypes.ViewModel;
using WheelsMarket.Services.VehicleTypeTypes;
using Microsoft.AspNetCore.Authorization;

namespace WheelsMarket.Controllers
{
    [Authorize(Roles = "Administrator")]
    public class BrandController:Controller
    {
        private readonly IBrandService brandService;

        public BrandController(IBrandService brandService)
        {
            this.brandService = brandService;
        }

        public async Task<IActionResult> Index()
        {
            var model = await brandService.ShowAllBrandAsync();

            return View(model);
        }

        [HttpGet] 
        public IActionResult Create()
        {
            ViewBag.VehicleTypeTypeId = this.brandService.AddBrandAdminAsync();

            return View();
        }
        [HttpPost]
        public async Task<IActionResult> Create(AddBrandViewModel model)
        {
            if (!ModelState.IsValid)
            {
                return View(model);
            }

            await brandService.AddBrandAdminAsync(model);
            return RedirectToAction("Index");
        }

        [HttpGet]
        public async Task<IActionResult> Delete(
            [FromRoute]
            Guid id)
        {
            await brandService.DeleteBrandAdminAsync(id);
            return RedirectToAction("Index");
        }

        [HttpGet]
        public async Task<IActionResult> Edit(Guid id)
        {
            Brand brand = await brandService.GetBrandIdAsync(id);

            if (brand != null)
            {
                EditBrandViewModel viewModel = new EditBrandViewModel()
                {
                    Id = brand.Id,
                    Name = brand.Name
                };
                return View("Edit", viewModel);
            }
            return RedirectToAction("Index");
        }

        [HttpPost]
        public async Task<IActionResult> Edit(EditBrandViewModel model)
        {
            if (ModelState.IsValid)
            {
                Brand brand = await brandService.GetBrandIdAsync(model.Id);

                if (brand != null)
                {
                    brand.Name = model.Name;

                    await brandService.EditBrandAsync(brand);

                    return RedirectToAction("Index");
                }
            }
            return View("Edit", model);
        }
    }
}

WheelsMarket/WheelsMarket/Controllers/EditionController.cs
using Microsoft.AspNetCore.Mvc;
using WheelsMarket.Services.VehicleTypeTypes.ViewModel;
using WheelsMarket.Services.VehicleTypeTypes;
using WheelsMarket.Services.Editions;
using WheelsMarket.Services.Editions.ViewModel;
using WheelsMarket.Data.Models;
using WheelsMarket.Services.Brands.ViewModel;
using WheelsMarket.Services.Brands;
using Microsoft.AspNetCore.Authorization;

namespace WheelsMarket.Controllers
{
    [Authorize(Roles = "Administrator")]
    public class EditionController:Controller
    {
        private readonly IEditionService editionService;

        public EditionController(IEditionService editionService)
        {
            this.editionService = editionService;
        }

        public async Task<IActionResult> Index()
        {
            var model = await editionService.ShowAllEditionAsync();
            return View(model);
        }

        [HttpGet]
        public IActionResult Create()
        {
            ViewBag.BrandId = this.editionService.AddEditionAsync();
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Create(AddEditionViewModel viewModel)
        {
            if (!ModelState.IsValid) { return View(viewModel); }
            await this.editionService.AddEditionAsync(viewModel);
            return RedirectToAction("Index", "Home");
        }

        [HttpGet]
        public async Task<IActionResult> Delete(
           [FromRoute]
            Guid id)
        {
            await editionService.DeleteEditionAsync(id);
            return RedirectToAction("Index");
        }

        [HttpGet]
        public async Task<IActionResult> Edit(Guid id)
        {
            Edition ediiton = await editionService.GetEditionIdAsync(id);

            if (ediiton != null)
            {
                EditEditionViewModel viewModel = new EditEditionViewModel()
                {
                    Id = ediiton.Id,
                    Name = ediiton.Name
                };
                return View("Edit", viewModel);
            }
            return RedirectToAction("Index");
        }

        [HttpPost]
        public async Task<IActionResult> Edit(EditEditionViewModel model)
        {
            if (ModelState.IsValid)
            {
                Edition edition = await editionService.GetEditionIdAsync(model.Id);

                if (edition != null)
                {
                    edition.Name = model.Name;

                    await editionService.EditEditionAsync(edition);

                    return RedirectToAction("Index");
                }
            }
            return View("Edit", model);
        }
    }
}

WheelsMarket/WheelsMarket/Controllers/VehicleTypeSectionController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using WheelsMarket.Data.Models;
using WheelsMarket.Services.VehicleTypeSections;
using WheelsMarket.Services.VehicleTypeSections.ViewModel;

namespace WheelsMarket.Controllers
{
    [Authorize(Roles = "Administrator")]
    public class VehicleTypeSectionController:Controller
    {
        private readonly IVehicleTypeSectionService vehicleTypeSectionService;

        public VehicleTypeSectionController(IVehicleTypeSectionService vehicleTypeSectionService)
        {
            this.vehicleTypeSectionService = vehicleTypeSectionService;
        }

        public async Task<IActionResult> Index()
        {
            var model = await vehicleTypeSectionService.ShowAllVehicleTypeSectionAsync();

            return View(model);
        }

        [HttpGet]
        public IActionResult Create()
        {
            return View();
        }
        [HttpPost]
        public async Task<IActionResult> Create(AddVehicleTypeSectionViewModel model)
        {
            if (!ModelState.IsValid)
            {
                return View(model);
            }
            await vehicleTypeSectionService.AddVehicleTypeSectionAsync(model);
            return RedirectToAction("Index");
        }


        [HttpGet]
        public async Task<IActionResult> Delete(
            [FromRoute]
            Guid id)
        {
            await vehicleTypeSectionService.DeleteVehicleTypeSectionAsync(id);
            return RedirectToAction("Index");
        }

		[HttpGet]
		public async Task<IActionResult> Edit(Guid id)
		{
		    VehicleTypeSection vts = await vehicleTypeSectionService.GetVehicleTypeSectionIdAsync(id);

			if (vts != null)
			{
				EditVehicleTypeSectionViewModel viewModel = new EditVehicleTypeSectionViewModel()
				{
					Id = vts.Id,
					Section = vts.Section,
				};
				return View("Edit", viewModel);
			}
			return RedirectToAction("Index");
		}

		[HttpPost]
		public async Task<IActionResult> Edit(EditVehicleTypeSectionViewModel model)
		{
			if (ModelState.IsValid)
			{
				VehicleTypeSection vts = await vehicleTypeSectionService.GetVehicleTypeSectionIdAsync(model.Id);

				if (vts != null)
				{
					vts.Section= model.Section;

					await vehicleTypeSectionService.EditVehicleTypeSectionAsync(vts);

					return RedirectToAction("Index");
				}
			}
			return View("Edit", model);
		}

	}
}

WheelsMarket/WheelsMarket/Controllers/VehicleTypeTypeController.cs
using Microsoft.AspNetCore.Mvc;
using WheelsMarket.Services.VehicleTypeSections.ViewModel;
using WheelsMarket.Services.VehicleTypeSections;
using WheelsMarket.Services.VehicleTypeTypes;
using WheelsMarket.Services.VehicleTypeTypes.ViewModel;
using Microsoft.AspNetCore.Mvc.Rendering;
using WheelsMarket.Data;
using WheelsMarket.Data.Models;
using Microsoft.AspNetCore.Authorization;

namespace WheelsMarket.Controllers
{
    [Authorize(Roles = "Administrator")]
    public class VehicleTypeTypeController:Controller
    {
        private readonly IVehicleTypeTypeService vehicleTypeTypeService;

        public VehicleTypeTypeController(IVehicleTypeTypeService vehicleTypeTypeService)
        {
            this.vehicleTypeTypeService = vehicleTypeTypeService;
        }

        public async Task<IActionResult> Index()
        {
            var model = await vehicleTypeTypeService.ShowAllVehicleTypeTypeAsync();

            return View(model);
        }

        [HttpGet]
        public IActionResult Create()
        {
            ViewBag.VehicleTypeSectionId = this.vehicleTypeTypeService.AddVehicleTypeTypeAsync();
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Create(AddVehicleTypeTypeViewModel viewModel)
        {
            if (!ModelState.IsValid) { return View(viewModel); }
            await this.vehicleTypeTypeService.AddVehicleTypeTypeAsync(viewModel);
            return RedirectToAction("Index");
        }

        [HttpGet]
        public async Task<IActionResult> Delete(
           [FromRoute]
            Guid id)
        {
            await vehicleTypeTypeService.DeleteVehicleTypeTypeAsync(id);
            return RedirectToAction("Index");
        }

        [HttpGet]
        public async Task<IActionResult> Edit(Guid id)
        {
            VehicleTypeType vtt = await vehicleTypeTypeService.GetVehicleTypeTypeIdAsync(id);

            if (vtt != null)
            {
                EditVehicleTypeTypeViewModel viewModel = new EditVehicleTypeTypeViewModel()
                {
                    Id = vtt.Id,
                    Type = vtt.Type
                };
                return View("Edit", viewModel);
            }
            return RedirectToAction("Index");
        }

        [HttpPost]
        public async Task<IActionResult> Edit(EditVehicleTypeTypeViewModel model)
        {
            if (ModelState.IsValid)
            {
                VehicleTypeType vtt = await vehicleTypeTypeService.GetVehicleTypeTypeIdAsync(model.Id);

                if (vtt != null)
                {
                    vtt.Type = model.Type;
                    //vts.VehicleTypeSectionId = model.VehicleTypeSectionsId;

                    await vehicleTypeTypeService.EditVehicleTypeTypeAsync(vtt);

                    return RedirectToAction("Index");
                }
            }
            return View("Edit", model);
        }
    }
}

WheelsMarket/WheelsMarket/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - WheelsMarket</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/style.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/WheelsMarket.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light border-bottom box-shadow mb-3" style="background-image: linear-gradient(to right, #090404, #650405, #090404); color: white">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index" style="color:white">WheelsMarket</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">

                    <ul class="navbar-nav flex-grow-1">
                        <style>
                            .nav-link:hover {
                                box-shadow: 0 12px 16px 0 rgba(0,0,0,0.24), 0 17px 50px 0 rgba(0,0,0,0.19);
                            }
                        </style>
                      
                        <li class="nav-item">
                            <a class="nav-link text-white" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                         @if (User.IsInRole("Administrator"))
                        {
                            <li class="nav-item">
                                <a class="nav-link text-white" asp-area="" asp-controller="VehicleTypeSection" asp-action="Index">Секции</a>
                            </li>

                            <li class="nav-item">
                                <a class="nav-link text-white" asp-area="" asp-controller="VehicleTypeType" asp-action="Index">Типове</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-white" asp-area="" asp-controller="Brand" asp-action="Index">Марки</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-white" asp-area="" asp-controller="Edition" asp-action="Index">Модели</a>
                            </li>
                        }
                        @if (User.IsInRole("Client"))
                        {
                        <li class="nav-item">
                            <a class="nav-link text-white" asp-area="" asp-controller="Vehicle" asp-action="Add">Добави</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-white" asp-area="" asp-controller="Vehicle" asp-action="VehicleFavourite">Любими</a>
                        </li>
                        }
                        @if (User.IsInRole("Administrator") || User.IsInRole("Client"))
                        {
                        <li class="nav-item">
                            <a class="nav-link text-white" asp-area="" asp-controller="Vehicle" asp-action="ShowSelectedInformationForAllVehicles">Разгледай</a>
                        </li>
                        }

                    </ul>
                    <partial name="_LoginPartial" />
                </div>
            </div>
        </nav>

    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

 
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>